import React from "react";
import Head from "next/head";
// import Image from "next/image";
// import styles from "../styles/Home.module.css";
// import Layout from "../Layout";
// import HomeMain from "../components/Home/HomeMain";

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>SAO Herbal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Home page</h1>
    </React.Fragment>
  );
}
